# Generated by Django 3.0.3 on 2020-04-22 14:55

import django.db.models.deletion
import yourplan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('report_to', models.CharField(max_length=50, null=True)),
                ('monthly_payment', models.CharField(max_length=15, null=True)),
                ('estimated_term', models.CharField(max_length=50, null=True)),
                ('estimated_amount', models.CharField(max_length=5, null=True)),
                ('payment_terms', models.CharField(max_length=50, null=True)),
                ('terms', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourplanyourplan_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'yourplan',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Viabill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'viabill',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sezzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourplansezzle_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'sezzle',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegularPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'regularpayment',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Quadpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourplanquadpay_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'quadpay',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourplanpaypal_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'paypal',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Klarna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourplanklarna_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'klarna',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceFactoringPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'invoicefactoringpayment',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FundBoxPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'fundboxpay',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Behalf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'behalf',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Affirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_owed', models.CharField(max_length=50)),
                ('financed_so_far', models.CharField(max_length=50)),
                ('payment_left', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'affirm',
            },
            bases=(yourplan.models.ModelMixin, models.Model),
        ),
    ]
