# Generated by Django 3.0.3 on 2020-04-26 20:54

import affiliate.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatewebinar_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_webinars',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountofresiduals', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliateresidual_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_residual',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaypalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatepaypalinformation_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_paypal_information',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_package', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatelead_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_lead',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankPaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_number', models.CharField(max_length=500, null=True)),
                ('name_of_bank', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=500, null=True)),
                ('name_on_bank_account', models.CharField(max_length=500, null=True)),
                ('your_address', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatebankpaymentinformation_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_bank_payment_information',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AffiliateAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliateaffiliateagents_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_affiliate_agents',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
    ]
