# Generated by Django 3.0.3 on 2020-04-26 21:32

import affiliate.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200420_0032'),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(max_length=50, null=True)),
                ('text_link', models.CharField(max_length=500, null=True)),
                ('email_link', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=500, null=True)),
                ('instagram', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatesharelinks_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_sharelink',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliatesale_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'affiliate_sale',
            },
            bases=(affiliate.models.ModelMixin, models.Model),
        ),
    ]
