# Generated by Django 3.0.5 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_sale_sharelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residual',
            name='amountofresiduals',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sharelinks',
            name='email_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sharelinks',
            name='facebook_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
