# Generated by Django 3.0.3 on 2020-04-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcourse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingCourse',
        ),
    ]
