# Generated by Django 3.0.5 on 2020-12-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0049_auto_20201208_1800'),
        ('financing_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Subdomain'),
        ),
    ]
