# Generated by Django 3.1.4 on 2021-01-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0003_auto_20210103_1648'),
        ('financing_portal', '0003_product_recurring'),
    ]

    operations = [
    ]
