# Generated by Django 3.1.4 on 2021-01-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0008_product_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default='One time', null=True),
        ),
    ]
