# Generated by Django 3.1.4 on 2021-01-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0010_auto_20210121_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
    ]
