# Generated by Django 3.1.1 on 2021-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing_portal', '0012_auto_20210123_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchasedmodel',
            name='logged_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
