# Generated by Django 3.0.5 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscreditcourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='estimated_amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='estimated_term',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='monthly_payment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='payment_terms',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='report_to',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='terms',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
