# Generated by Django 3.2.5 on 2021-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscreditcourse', '0002_auto_20200514_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscreditcourse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
