# Generated by Django 3.0.5 on 2020-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('webinar', models.URLField()),
                ('iphoneApp', models.URLField()),
                ('androidApp', models.URLField()),
                ('chromeExt', models.URLField()),
                ('homeVideo', models.URLField()),
            ],
        ),
    ]
