# Generated by Django 3.0.5 on 2020-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='androidApp',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='chromeExt',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='homeVideo',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='iphoneApp',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='sub_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='webinar',
            field=models.URLField(max_length=300),
        ),
    ]
