# Generated by Django 3.0.5 on 2020-08-25 19:09

from django.db import migrations, models
import django.utils.timezone
# import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_auto_20200824_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdomain',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subdomain',
            name='phno',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
