# Generated by Django 3.0.5 on 2020-08-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_auto_20200826_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='fav_icon',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
