# Generated by Django 3.0.5 on 2020-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_subdomain_fav_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='phno',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
