# Generated by Django 3.0.5 on 2020-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_subdomain_fav_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
