# Generated by Django 3.0.5 on 2020-08-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_auto_20200826_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Subdomain',
            name='fav_icon',
        ),
    ]
