# Generated by Django 3.0.5 on 2020-08-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_remove_subdomain_fav_icon'),
        ('dynamic', '0005_subdomain_is_payment_done'),
    ]

    operations = [
    ]
