# Generated by Django 3.0.5 on 2020-08-27 09:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_merge_20200827_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='fav_icon',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='phno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
