# Generated by Django 3.0.5 on 2020-08-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_auto_20200827_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='why_buy_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
