# Generated by Django 3.0.5 on 2020-08-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_subdomain_why_buy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='appImage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
