# Generated by Django 3.0.5 on 2020-08-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0010_subdomain_appimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_btn_col', models.CharField(blank=True, max_length=300)),
                ('nav_btn_h_col', models.CharField(blank=True, max_length=200)),
                ('nav_btn_a_col', models.CharField(blank=True, max_length=200)),
                ('nav_btn_a_h_col', models.CharField(blank=True, max_length=200)),
                ('theme_btn_col', models.CharField(blank=True, max_length=200)),
                ('theme_btn_a_col', models.CharField(blank=True, max_length=200)),
                ('login_bg_col', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
