# Generated by Django 3.0.5 on 2020-08-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0011_themecolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themecolor',
            old_name='login_bg_col',
            new_name='login_bg_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='nav_btn_a_col',
            new_name='nav_btn_a_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='nav_btn_a_h_col',
            new_name='nav_btn_a_h_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='nav_btn_col',
            new_name='nav_btn_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='nav_btn_h_col',
            new_name='nav_btn_h_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='theme_btn_a_col',
            new_name='theme_btn_a_color',
        ),
        migrations.RenameField(
            model_name='themecolor',
            old_name='theme_btn_col',
            new_name='theme_btn_color',
        ),
    ]
