# Generated by Django 3.0.5 on 2020-08-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0012_auto_20200829_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeColor',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='accent_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bg_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='primary_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
