# Generated by Django 3.0.5 on 2020-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0013_auto_20200829_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='fav_icon',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
