# Generated by Django 3.0.5 on 2020-08-29 19:21

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0013_auto_20200829_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='fav_icon',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='logo',
            field=models.ImageField(blank=True, upload_to=services.FileServices.get_file_path),
        ),
    ]
