# Generated by Django 3.0.5 on 2020-08-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0015_auto_20200829_2348'),
        ('dynamic', '0014_auto_20200829_1921'),
    ]

    operations = [
    ]
