# Generated by Django 3.0.5 on 2020-08-30 15:04

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0017_auto_20200830_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='accent_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bg_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='logo',
            field=models.ImageField(upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='primary_color',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
