# Generated by Django 3.1.1 on 2020-09-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_auto_20200902_1204'),
        ('dynamic', '0018_auto_20200830_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='admins',
            field=models.ManyToManyField(to='user.Profile'),
        ),
    ]
