# Generated by Django 3.1.1 on 2020-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_delete_usersteps'),
        ('dynamic', '0019_subdomain_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='admins',
            field=models.ManyToManyField(related_name='portals', to='user.Profile'),
        ),
    ]
