# Generated by Django 3.1.1 on 2020-09-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0021_subdomain_extensionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='creditRepairLink',
            field=models.CharField(default='/business/credit-affiliate', max_length=300, null=True),
        ),
    ]
