# Generated by Django 3.1.1 on 2020-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0022_subdomain_creditrepairlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='faq_page',
            field=models.CharField(default='https://businessbuilders.zendesk.com/hc/en-us/sections/360010349512-FAQ', max_length=300, null=True),
        ),
    ]
