# Generated by Django 3.1.1 on 2020-09-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0023_subdomain_faq_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='why_buy_link',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/bM8A5BDZglk', max_length=200),
        ),
    ]
