# Generated by Django 3.1.1 on 2020-11-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0024_auto_20200929_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='portal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Portal price'),
        ),
    ]
