# Generated by Django 3.1.1 on 2020-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0026_auto_20201105_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='is_main_site',
            field=models.BooleanField(default=False),
        ),
    ]
