# Generated by Django 3.1.1 on 2020-11-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0027_subdomain_is_main_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='show_index_white_label',
            field=models.BooleanField(default=True),
        ),
    ]
