# Generated by Django 3.1.1 on 2020-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0028_subdomain_show_index_white_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='show_index_white_label',
            field=models.BooleanField(default=False),
        ),
    ]
