# Generated by Django 3.1.1 on 2020-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0029_auto_20201106_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='appointment_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='show_affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='show_appointment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='show_becoming_whitelabel_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='show_whitelabel_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='whitelabelpartner_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
