# Generated by Django 3.1.1 on 2020-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0030_auto_20201106_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='whitelabel_index_video',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
