# Generated by Django 3.1.1 on 2020-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0033_subdomain_show_why_buy_from_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='show_free_access_to_affiliate_program',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='show_money_back_guarantee',
            field=models.BooleanField(default=True),
        ),
    ]
