# Generated by Django 3.1.1 on 2020-11-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0035_auto_20201109_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='offer_paid_whitelabel',
            field=models.BooleanField(default=False),
        ),
    ]
