# Generated by Django 3.1.1 on 2020-11-13 08:34

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0036_subdomain_offer_paid_whitelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='favicon_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='frontpage_text',
            field=models.TextField(null=True, verbose_name='Main text'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='seo_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
