# Generated by Django 3.1.1 on 2020-11-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0037_auto_20201113_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='aboutus_text',
            field=models.TextField(default='Get Dinero Today offers a wide range of services. Which include getting clients loans, building business credit, $1,500 in free marketing, business credit course, autodialer, website builder and much more. Our business builder program helps you with each step of the business credit building process.', null=True, verbose_name='About Us text'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='frontpage_text',
            field=models.TextField(default='We Help Businesses Acquire Business Credit With Our Free Software, Mobile App, & Google Chrome Extension. Also, We Have A Free Personal Credit, Marketing, & Business Credit Course In Our Software As Well. Get $1,500 In Free Marketing, & Only Pay For Real Services Only When You Need It & Would Like To Upgrade & Purchase Our Business Credit Builder Package.', null=True, verbose_name='Main text'),
        ),
    ]
