# Generated by Django 3.1.1 on 2020-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0038_auto_20201113_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='credit_repair_consultation_link',
            field=models.CharField(blank=True, default='https://shareasale.com/r.cfm?b=520260&u=2228198&m=49614&urllink=&afftrack=', max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='credit_repair_service_button_text',
            field=models.CharField(blank=True, default='Click Here To Get Your Free Consultation', max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='credit_repair_service_image',
            field=models.CharField(blank=True, default='https://www.creditfirm.net/wp-content/uploads/2012/06/CreditFirm-Logo-300x182.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='credit_repair_service_text',
            field=models.TextField(default='Click The Button Below To Have One On One Credit Repair <br> Start Fixing Your Credit For As Low As $49.99 Per Month', null=True),
        ),
    ]
