# Generated by Django 3.1.1 on 2020-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0039_auto_20201113_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='is_paid_for_whitelabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='show_free_access_to_affiliate_program',
            field=models.BooleanField(default=False),
        ),
    ]
