# Generated by Django 3.1.1 on 2020-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0040_auto_20201115_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='favicon_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Tab Title'),
        ),
    ]
