# Generated by Django 3.1.1 on 2020-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0041_auto_20201117_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='login_window_color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
