# Generated by Django 3.1.1 on 2020-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0042_subdomain_login_window_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='appImage',
            field=models.CharField(blank=True, default='/static/images/thebusinessbuildersapp.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='credit_repair_service_text',
            field=models.TextField(default='Click The Button Below To Have One On One Credit Repair \nStart Fixing Your Credit For As Low As $49.99 Per Month', null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='email',
            field=models.CharField(blank=True, default='info@businesscreditbuildersllc.com', max_length=200, null=True),
        ),
    ]
