# Generated by Django 3.1.1 on 2020-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0045_auto_20201119_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='sub_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
