# Generated by Django 3.1.1 on 2020-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0046_auto_20201119_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='accent_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bg_color',
            field=models.CharField(blank=True, default='#333333', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='extensionVideo',
            field=models.URLField(default='https://www.youtube.com/watch?v=Z1HK9uSOMCI', max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='homeVideo',
            field=models.URLField(default='https://youtu.be/xNCfnbGT5hY', max_length=300),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='login_window_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=200),
        ),
    ]
