# Generated by Django 3.1.1 on 2020-11-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0047_auto_20201120_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='accent_color',
            field=models.CharField(blank=True, default='#115d22', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='primary_color',
            field=models.CharField(blank=True, default='#916e06', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='secondary_color',
            field=models.CharField(blank=True, default='#fffff', max_length=200),
        ),
    ]
