# Generated by Django 3.1.1 on 2020-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0048_auto_20201120_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='basic_partnership_program_price',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=50, verbose_name='Basic Partnership Program Price Annual'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='offer_paid_whitelabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='premium_partnership_program_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=50, verbose_name='Premium Partnership Program Price Monthly'),
        ),
    ]
