# Generated by Django 3.1.1 on 2021-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0049_auto_20201208_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='concierge_program_price',
            field=models.DecimalField(decimal_places=2, default=3999.0, max_digits=50, verbose_name='Concierge Program Price Yearly'),
        ),
    ]
