# Generated by Django 3.1.1 on 2021-02-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0051_subdomain_life_insurance_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='show_life_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
