# Generated by Django 3.1.7 on 2021-03-12 19:04

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20210312_1841'),
        ('dynamic', '0053_auto_20210305_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='portals', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
    ]
