# Generated by Django 3.2.5 on 2021-07-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0056_auto_20210714_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='business_credit_course_video_link',
            field=models.CharField(blank=True, help_text='add the video that you want to show on the https://<Site Name>/businesscreditcourse/ ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='business_credit_course_video_link_text',
            field=models.CharField(blank=True, help_text='add the text that you want to show on the https://<Site Name>/businesscreditcourse/ ', max_length=200, null=True),
        ),
    ]
