# Generated by Django 3.2.5 on 2021-07-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0057_auto_20210714_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='business_credit_course_video_link',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/jj6AyUyl15Y', help_text='add the video that you want to show on the https://<Site Name>/businesscreditcourse/ ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='business_credit_course_video_link_text',
            field=models.CharField(blank=True, default='Watch The Video Above To Get An Introduction To The Business Credit Building Course Portal', help_text='add the text that you want to show on the https://<Site Name>/businesscreditcourse/ ', max_length=200, null=True),
        ),
    ]
