# Generated by Django 3.2.5 on 2021-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0058_auto_20210714_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='show_business_credit_course',
            field=models.BooleanField(default=True),
        ),
    ]
