# Generated by Django 3.2.5 on 2021-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0059_subdomain_show_business_credit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='business_credit_course_video_Heading',
            field=models.CharField(default='Business Credit Course', max_length=200),
        ),
    ]
