# Generated by Django 3.2.5 on 2021-07-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0060_subdomain_business_credit_course_video_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='business_credit_course_video_Heading',
            field=models.CharField(default='Business Credit Course', help_text='add the heading for your video heading on /businesscreditcourse/', max_length=200),
        ),
    ]
