# Generated by Django 3.2.5 on 2021-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0064_auto_20210714_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='business_credit_course_video_link',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/jj6AyUyl15Y', help_text='add the iframe that you want to show on the https://<Site Name>/businesscreditcourse/ ', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='personal_credit_course_video_link',
            field=models.CharField(blank=True, default='https://youtu.be/0JMgyfFZfiE', help_text='add the iframe  that you want to show on the /creditcourse/maincreditfile ', max_length=2000, null=True),
        ),
    ]
