# Generated by Django 3.2.5 on 2021-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0065_auto_20210714_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='whitelabel_partener_paid',
            field=models.BooleanField(default=False, help_text='Check the box if the client has paid for the whitelabel partner program'),
        ),
    ]
