# Generated by Django 3.2.5 on 2021-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0066_subdomain_whitelabel_partener_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='whitelabel_partener_paid',
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='is_paid_for_whitelabel',
            field=models.BooleanField(default=False, help_text='check the box if the client has paid for the whitelabel program'),
        ),
    ]
