# Generated by Django 3.2.5 on 2021-07-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0068_auto_20210715_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='navigation_bar_link_2_Link',
            new_name='navigation_bar_link_2_link',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='navigation_bar_link_3_Link',
            new_name='navigation_bar_link_3_link',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='navigation_bar_link_6_Link',
            new_name='navigation_bar_link_6_link',
        ),
        migrations.RemoveField(
            model_name='subdomain',
            name='first_package_1_button_link',
        ),
    ]
