# Generated by Django 3.2.5 on 2021-07-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0069_auto_20210716_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdomain',
            old_name='navigation_bar_link_4_Link',
            new_name='navigation_bar_link_4_link',
        ),
        migrations.RenameField(
            model_name='subdomain',
            old_name='navigation_bar_link_5_Link',
            new_name='navigation_bar_link_5_link',
        ),
    ]
