# Generated by Django 3.2.5 on 2021-07-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0070_auto_20210716_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='first_package_1_button_link',
            field=models.CharField(blank=True, default='/user/login', help_text='paste the link where you want your button to get dirrected to ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_1_bullet_point',
            field=models.CharField(blank=True, default='Create My Financing Plan Access', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_1_button_text',
            field=models.CharField(blank=True, default='Sign Up For Forever Free Package', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_2_bullet_point',
            field=models.CharField(blank=True, default='Create My Business Credit Building Plan Access', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_2_show_button',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_3_bullet_point',
            field=models.CharField(blank=True, default='Apply For Business Loan Access To Get Best Rates', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_4_bullet_point',
            field=models.CharField(blank=True, default='Business Credit Building Course (Usually $1,000)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_5_bullet_point',
            field=models.CharField(blank=True, default='Full Starter Vendor, Retail Store Credit, Revolving Store Credit, & Cash\n                                                    Credit\n                                                    List', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_6_bullet_point',
            field=models.CharField(blank=True, default='Your Own Backend Client Portal To Track Progress', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_7_bullet_point',
            field=models.CharField(blank=True, default='Full Access To Our Create My Financing Plan Section(*You Get Your Own\n                                                                                                                                 Financing\n                                                                                                                                 Plan Based On Your Current Situation * & Access To 300 + Lenders)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_8_bullet_point',
            field=models.CharField(blank=True, default='Create My Credit Repair Plan Access', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_1_bullet_point',
            field=models.CharField(blank=True, default=' We help you get $50,000 in business vendor credit, we set up your business\n                                        credibly,\n                                        and manage your account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_1_button_link',
            field=models.CharField(blank=True, default='/user/login', help_text='paste the link where you want your button to get dirrected to ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_1_button_text',
            field=models.CharField(blank=True, default='${{yearly}} Annual Payment Option', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_2_bullet_point',
            field=models.CharField(blank=True, default='Create My Financing Plan Access', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_2_button_link',
            field=models.CharField(blank=True, default='/user/login', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_2_button_text',
            field=models.CharField(blank=True, default=' ${{ monthly }} Monthly Payment Option', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_3_bullet_point',
            field=models.CharField(blank=True, default='Create My Business Credit Building Plan Access', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_4_bullet_point',
            field=models.CharField(blank=True, default='Apply For Business Loan Access To Get Best Rates', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_5_bullet_point',
            field=models.CharField(blank=True, default='Website Design (Usually $2,000+)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_6_bullet_point',
            field=models.CharField(blank=True, default='Free Web Hosting For The Entire Year', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_7_bullet_point',
            field=models.CharField(blank=True, default='We Buy Your Fax Number For Entire Year(Usually $100+)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_8_bullet_point',
            field=models.CharField(blank=True, default='Professional Email (Usually $100+) and much more', max_length=200, null=True),
        ),
    ]
