# Generated by Django 3.2.5 on 2021-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0075_subdomain_show_bcb_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo_link',
            field=models.ImageField(blank=True, default='https://bcbvideosoftware.com/', null=True, upload_to=''),
        ),
    ]
