# Generated by Django 3.2.5 on 2021-08-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0076_alter_subdomain_bcb_video_software_logo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo',
            field=models.ImageField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo_link',
            field=models.TextField(blank=True, default='https://bcbvideosoftware.com/', null=True),
        ),
    ]
