# Generated by Django 3.2.5 on 2021-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0077_auto_20210810_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to='bcbsoftwares/'),
        ),
    ]
