# Generated by Django 3.2.5 on 2021-08-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0078_alter_subdomain_bcb_video_software_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
    ]
