# Generated by Django 3.2.5 on 2021-08-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0079_alter_subdomain_bcb_video_software_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='bcb_projectmanagment_software_heading',
            field=models.CharField(blank=True, default='Trello helps teams move work forward.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_projectmanagment_software_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_projectmanagment_software_text',
            field=models.CharField(blank=True, default='Collaborate, manage projects, and reach new productivity peaks. From high rises to the home office, the way your team works is unique—accomplish it all with Trello.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
