# Generated by Django 3.2.5 on 2021-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0080_auto_20210810_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='bcb_projectmanagment_software_logo_link',
            field=models.TextField(blank=True, default='https://bcbprojectmanagement.com/', null=True),
        ),
    ]
