# Generated by Django 3.2.5 on 2021-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0083_auto_20210810_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='first_package_7_bullet_point',
            field=models.CharField(blank=True, default='Full Access To Our Create My Financing Plan Section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_1_button_text',
            field=models.CharField(blank=True, default='$999 Yearly Payment Option', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='second_package_2_button_text',
            field=models.CharField(blank=True, default=' $109 Monthly Payment ', max_length=200, null=True),
        ),
    ]
