# Generated by Django 3.2.5 on 2021-08-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0085_auto_20210814_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='bcb_accounting_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_accounting_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_accounting_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_accounting_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_accounting_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_appointment_software_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_appointment_software_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_appointment_software_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_appointment_software_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_appointment_software_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_filesharing_software_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_filesharing_software_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_filesharing_software_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_filesharing_software_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_filesharing_software_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_marketing_automation_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_marketing_automation_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_marketing_automation_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_marketing_automation_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_marketing_automation_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_text_marketing_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_text_marketing_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_text_marketing_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_text_marketing_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_text_marketing_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_video_conferencing_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_video_conferencing_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_video_conferencing_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_video_conferencing_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_video_conferencing_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_voice_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_voice_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_voice_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_voice_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_voice_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_web_hosting_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_web_hosting_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_web_hosting_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_web_hosting_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_web_hosting_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_website_builder_bottom_heading',
            field=models.CharField(blank=True, default='Refreshing business software that your teams will love', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_website_builder_heading',
            field=models.CharField(blank=True, default='Best-in-class customer and employee engagement', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_website_builder_logo',
            field=models.CharField(blank=True, default='https://kleui.s3.amazonaws.com/documents/fe7e8fd5-3607-4e5b-b502-c5fc3819aa1e/Kleui-03-r.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_website_builder_logo_link',
            field=models.TextField(blank=True, default='https://bcbcrmsoftware.com/', null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='bcb_website_builder_text',
            field=models.CharField(blank=True, default='A software suite that is intuitive and easy to use so you have a happy and engaged workforce who in turn help you build and create lasting relationships with customers for life.', max_length=500, null=True),
        ),
    ]
