# Generated by Django 3.2.5 on 2021-08-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0086_auto_20210814_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='navigation_bar_link_2_text',
            field=models.CharField(default='About Us', help_text='add the text that you want to show in the first link in the navbar', max_length=200),
        ),
    ]
