# Generated by Django 3.2.5 on 2021-09-24 15:27

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0087_alter_subdomain_navigation_bar_link_2_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='bcb_crm_software_logo_link',
        ),
        migrations.AddField(
            model_name='subdomain',
            name='footer_text',
            field=models.TextField(default='We Help Businesses Acquire Business Credit With Our Free Software, Mobile App, & Google Chrome Extension. Also, We Have A Free Personal Credit, Marketing, & Business Credit Course In Our Software As Well.', max_length=500, verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_accounting_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_appointment_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_crm_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_filesharing_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_marketing_automation_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_projectmanagment_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_seo_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_text_marketing_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_conferencing_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_video_software_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_voice_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_web_hosting_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='bcb_website_builder_logo',
            field=models.ImageField(blank=True, null=True, upload_to=services.FileServices.get_file_path),
        ),
    ]
