# Generated by Django 3.0.5 on 2020-05-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nopg',
            old_name='url',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='nopg',
            old_name='payment_terms',
            new_name='estimated_amount',
        ),
        migrations.RenameField(
            model_name='nopg',
            old_name='estimated_term',
            new_name='reports_to',
        ),
        migrations.RenameField(
            model_name='nopg',
            old_name='monthly_payment',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='nopg',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nopg',
            name='report_to',
        ),
    ]
