# Generated by Django 3.0.5 on 2020-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200501_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nopg',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
