# Generated by Django 3.0.5 on 2020-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20200501_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nopg',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='estimated_amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='reports_to',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='terms',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
