# Generated by Django 3.0.5 on 2020-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200501_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revolvingcredit',
            name='category',
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='report_to',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='terms',
            field=models.CharField(max_length=200),
        ),
    ]
