# Generated by Django 3.0.5 on 2020-05-04 15:54

import business.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200501_0959'),
        ('business', '0008_auto_20200501_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experian', models.CharField(max_length=50)),
                ('equifax', models.CharField(max_length=50)),
                ('transunion', models.CharField(max_length=50)),
                ('monthly_revenue_3', models.CharField(max_length=50)),
                ('daily_balance_3', models.CharField(max_length=50)),
                ('monthlty_ending_balance_3', models.CharField(max_length=50)),
                ('monthly_revenue_6', models.CharField(max_length=50)),
                ('daily_balance_6', models.CharField(max_length=50)),
                ('monthlty_ending_balance_6', models.CharField(max_length=50)),
                ('business_revenue', models.CharField(max_length=50)),
                ('nonsufficient_6', models.CharField(max_length=50)),
                ('nonsufficient_12', models.CharField(max_length=50)),
                ('current_liens', models.CharField(max_length=50)),
                ('business_account', models.CharField(max_length=50)),
                ('business_loan', models.CharField(max_length=50)),
                ('business_age', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'financing_information',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
