# Generated by Django 3.0.5 on 2020-05-06 12:08

import business.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200501_0959'),
        ('business', '0009_financinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRepairInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experian_score', models.CharField(max_length=50)),
                ('equifax_score', models.CharField(max_length=50)),
                ('transunion_score', models.CharField(max_length=50)),
                ('experian_utilization', models.CharField(max_length=50)),
                ('equifax_utilization', models.CharField(max_length=50)),
                ('transunion_utilization', models.CharField(max_length=50)),
                ('current_collections', models.CharField(max_length=50)),
                ('bankruptcies', models.CharField(max_length=50)),
                ('bankruptcies_10', models.CharField(max_length=50)),
                ('inquiries', models.CharField(max_length=50)),
                ('missed_payments', models.CharField(max_length=50)),
                ('current_acc_experian', models.CharField(max_length=50)),
                ('current_acc_equifax', models.CharField(max_length=50)),
                ('current_acc_transunion', models.CharField(max_length=50)),
                ('credit_history_experian', models.CharField(max_length=50)),
                ('credit_history_equifax', models.CharField(max_length=50)),
                ('credit_history_transunion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'db_table': 'credit_repair_information',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
