# Generated by Django 3.0.5 on 2020-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businesscreditinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscreditinformation',
            name='business_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesscreditinformation',
            name='trade_lines',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
