# Generated by Django 3.0.5 on 2020-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20200507_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storecreditvendorlist',
            old_name='apr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='storecreditvendorlist',
            old_name='business_revenue',
            new_name='estimated_amount',
        ),
        migrations.RenameField(
            model_name='storecreditvendorlist',
            old_name='lender_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='storecreditvendorlist',
            old_name='personal_credit_score',
            new_name='reports_to',
        ),
        migrations.RenameField(
            model_name='storecreditvendorlist',
            old_name='strategy',
            new_name='terms',
        ),
        migrations.RemoveField(
            model_name='storecreditvendorlist',
            name='term_length',
        ),
        migrations.RemoveField(
            model_name='storecreditvendorlist',
            name='time_in_business',
        ),
    ]
