# Generated by Django 3.0.5 on 2020-05-13 13:38

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20200513_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoCreditCheckLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=50, null=True)),
                ('estimated_terms', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nocreditcheck_loans',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
