# Generated by Django 3.0.5 on 2020-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20200514_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscreditcard',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='financingplanregularperson',
            name='description',
            field=models.CharField(max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='financingplanregularperson',
            name='estimated_amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='financingplanregularperson',
            name='monthly_payment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='description',
            field=models.CharField(max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='estimated_amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lender',
            name='monthly_payment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nocreditcheckloans',
            name='estimated_terms',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nocreditcheckloans',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='estimated_amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='reports_to',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nopg',
            name='terms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personalcreditcard',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='personalcredittradeline',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='revolvingbusinesscreditvendor',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='report_to',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='revolvingcredit',
            name='terms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='startervendorlist',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='storecreditvendorlist',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storecreditvendorlist',
            name='estimated_amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storecreditvendorlist',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storecreditvendorlist',
            name='reports_to',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='storecreditvendorlist',
            name='terms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='websitecreation',
            name='about_you',
            field=models.CharField(max_length=5500),
        ),
        migrations.AlterField(
            model_name='websitecreation',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
