# Generated by Django 3.0.5 on 2020-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20200514_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startervendorlist',
            old_name='report_to',
            new_name='estimated_amount',
        ),
        migrations.RemoveField(
            model_name='startervendorlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='startervendorlist',
            name='url',
        ),
        migrations.AddField(
            model_name='startervendorlist',
            name='estimated_terms',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startervendorlist',
            name='monthly_payment',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startervendorlist',
            name='payment_terms',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startervendorlist',
            name='reports_to',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
