# Generated by Django 3.0.5 on 2020-05-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20200514_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startervendorlist',
            old_name='reports_to',
            new_name='report_to',
        ),
    ]
