# Generated by Django 3.0.5 on 2020-05-24 09:26

import business.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200522_1212'),
        ('business', '0020_auto_20200514_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCreditSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5000, null=True)),
                ('last_name', models.CharField(max_length=5000, null=True)),
                ('email', models.CharField(max_length=5000, null=True)),
                ('phone', models.CharField(max_length=5000, null=True)),
                ('website', models.BooleanField(default=False)),
                ('fax', models.BooleanField(default=False)),
                ('toll_free_number', models.BooleanField(default=False)),
                ('domain', models.BooleanField(default=False)),
                ('pro_email_address', models.BooleanField(default=False)),
                ('website_inndustry', models.CharField(blank=True, choices=[('1', 'Dentist'), ('2', 'Real Estate'), ('3', 'Restaurant'), ('4', 'Auto Repair'), ('5', 'Trucking'), ('6', 'Hair Salon'), ('7', 'Transportation Services'), ('8', 'Electrician'), ('9', 'Lawyer'), ('10', 'Photography'), ('11', 'Landscaping'), ('12', 'Musician'), ('13', 'Ecommece'), ('14', 'Insurance Agent'), ('15', 'Accountant'), ('16', 'Carpet & Flooring'), ('17', 'Barber'), ('18', 'Spa'), ('19', 'Wedding Planner')], max_length=5000, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'verbose_name': 'Business Credit steps',
                'verbose_name_plural': 'Business Credit steps',
            },
            bases=(business.models.ModelMixin, models.Model),
        ),
    ]
