# Generated by Django 3.1.1 on 2020-12-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_auto_20200524_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('tradeline_credit_amount', models.CharField(max_length=500)),
                ('reports_to', models.CharField(max_length=500)),
                ('we_can_help', models.BooleanField(default=True, null=True)),
                ('recommended', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('tradeline_credit_amount', models.CharField(max_length=500)),
                ('reports_to', models.CharField(max_length=500)),
                ('we_can_help', models.BooleanField(default=True, null=True)),
                ('recommended', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('tradeline_credit_amount', models.CharField(max_length=500)),
                ('reports_to', models.CharField(max_length=500)),
                ('we_can_help', models.BooleanField(default=True, null=True)),
                ('recommended', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='personalcredittradeline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalcredittradeline',
            name='lender_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personalcredittradeline',
            name='strategy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
