# Generated by Django 3.1.1 on 2020-12-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0027_auto_20201209_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTradelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('tradeline_credit_amount', models.CharField(max_length=500)),
                ('reports_to', models.CharField(max_length=500)),
                ('we_can_help', models.BooleanField(default=True, null=True)),
                ('recommended', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
