# Generated by Django 3.1.1 on 2020-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_currenttradelines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier1',
            name='recommended',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier2',
            name='recommended',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier3',
            name='recommended',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tier4',
            name='recommended',
            field=models.TextField(blank=True, null=True),
        ),
    ]
