# Generated by Django 3.1.1 on 2020-12-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20201209_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tier2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tier3',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tier4',
            name='user',
        ),
    ]
