# Generated by Django 3.1.1 on 2020-12-09 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0049_auto_20201208_1800'),
        ('business', '0030_auto_20201209_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier1',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier1',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier1',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='price_lookup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
        migrations.AddField(
            model_name='tier2',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier2',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier2',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='price_lookup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
        migrations.AddField(
            model_name='tier3',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier3',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier3',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='price_lookup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
        migrations.AddField(
            model_name='tier4',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier4',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tier4',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='price_lookup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
    ]
