# Generated by Django 3.1.1 on 2020-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20201209_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tier1',
            old_name='business_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='tier2',
            old_name='business_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='tier3',
            old_name='business_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='tier4',
            old_name='business_name',
            new_name='company_name',
        ),
    ]
