# Generated by Django 3.1.1 on 2020-12-09 15:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0049_auto_20201208_1800'),
        ('business', '0035_auto_20201209_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('tradeline_amount', models.CharField(max_length=500)),
                ('tradeline_credit_amount', models.CharField(max_length=500)),
                ('company_reports_to', models.CharField(max_length=500)),
                ('we_can_help', models.BooleanField(default=True, null=True)),
                ('recommended', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price_lookup', models.CharField(blank=True, max_length=100, null=True)),
                ('whitelabel_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
