# Generated by Django 3.1.1 on 2020-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20201209_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtier',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tier1',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tier2',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tier3',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tier4',
            name='tier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
