# Generated by Django 3.1.1 on 2020-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_credibilitysteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='credibilitysteps',
            name='bankaccount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='ein',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='entity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='four11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credibilitysteps',
            name='website',
            field=models.BooleanField(default=False),
        ),
    ]
