# Generated by Django 3.1.1 on 2020-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_othercheckliststeps'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercheckliststeps',
            name='tier1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othercheckliststeps',
            name='tier2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othercheckliststeps',
            name='tier3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othercheckliststeps',
            name='tier4',
            field=models.BooleanField(default=False),
        ),
    ]
