# Generated by Django 3.1.1 on 2020-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_auto_20201215_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercheckliststeps',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
