# Generated by Django 3.1.4 on 2021-01-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_auto_20210103_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtier',
            name='name',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customtier',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='name',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='name',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='name',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='name',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Month'), (3, 'Year')], default=1, null=True),
        ),
    ]
