# Generated by Django 3.1.4 on 2021-01-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0046_auto_20210121_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtier',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtier',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
