# Generated by Django 3.1.4 on 2021-01-22 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_auto_20210122_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customtier',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='tier1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tier1',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='tier2',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tier2',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='tier3',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tier3',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='tier4',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tier4',
            name='terms',
        ),
    ]
