# Generated by Django 3.1.4 on 2021-01-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0048_auto_20210122_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customtier',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier1',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier2',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier3',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tier4',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
