# Generated by Django 3.2.5 on 2022-11-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0055_navigationlinks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='navigationlinks',
            table='navigation_link',
        ),
    ]
