# Generated by Django 3.2.5 on 2023-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0056_alter_navigationlinks_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_1', models.CharField(blank=True, default='', max_length=50)),
                ('column_2', models.CharField(blank=True, default='', max_length=50)),
                ('column_3', models.CharField(blank=True, default='', max_length=50)),
                ('column_4', models.CharField(blank=True, default='', max_length=50)),
                ('column_5', models.CharField(blank=True, default='', max_length=50)),
                ('column_6', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='is_every_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='is_main_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigationlinks',
            name='is_whitelabel_site',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=100)),
                ('is_main_site', models.BooleanField(default=False)),
                ('is_every_site', models.BooleanField(default=False)),
                ('is_whitelabel_site', models.BooleanField(default=False)),
                ('column_name_1', models.CharField(blank=True, default='', max_length=50)),
                ('column_name_2', models.CharField(blank=True, default='', max_length=50)),
                ('column_name_3', models.CharField(blank=True, default='', max_length=50)),
                ('column_name_4', models.CharField(blank=True, default='', max_length=50)),
                ('column_name_5', models.CharField(blank=True, default='', max_length=50)),
                ('column_name_6', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.ManyToManyField(blank=True, to='business.PageData')),
            ],
        ),
    ]
