# Generated by Django 3.0.5 on 2020-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_remove_virtualcard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='virtual_access_card_paid',
            field=models.BooleanField(default=False),
        ),
    ]
