# Generated by Django 3.0.5 on 2020-05-01 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_profile_virtual_access_card_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='virtual_card', to=settings.AUTH_USER_MODEL),
        ),
    ]
