# Generated by Django 3.0.5 on 2020-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_auto_20200501_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Portal Name')),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portals',
            },
        ),
    ]
