# Generated by Django 3.0.5 on 2020-05-06 08:09

from django.db import migrations


def create_portals(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Portal = apps.get_model("user", "Portal")
    db_alias = schema_editor.connection.alias
    Portal.objects.using(db_alias).bulk_create([
        Portal(name="Fitness Portal"),
        Portal(name="Medical Portal"),
        Portal(name="Real Estate Portal"),
        Portal(name="Restaurant & Catering Portal"),
        Portal(name="Automotive Portal"),
        Portal(name="Car Dealership Portal"),
        Portal(name="Trucking Portal"),
        Portal(name="Hair Salon Portal"),
        Portal(name="Lawyer Portal"),
        Portal(name="Photography Portal"),
        Portal(name="Transportation Portal"),
        Portal(name="Electrician Portal"),
        Portal(name="Landscaping Portal"),
        Portal(name="eCommerce Portal"),
        Portal(name="Musician Portal"),
        Portal(name="Insurance Agent Portal"),
        Portal(name="Handy Man Services Portal"),
        Portal(name="Accountant Portal"),
        Portal(name="Dentist Portal"),
        Portal(name="Carpet & Flooring Portal"),
        Portal(name="Cannabis Portal"),
        Portal(name="Wholesaler Portal"),
        Portal(name="Barber Portal"),
        Portal(name="Spa Business Portal"),
        Portal(name="Physcial Therapist Portal"),
        Portal(name="Credit Repair Company Portal"),
        Portal(name="Wedding Planner Portal"),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0008_portal'),
    ]

    operations = [
        migrations.RunPython(create_portals),
    ]
