# Generated by Django 3.0.5 on 2020-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_profile_portals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='portals',
            field=models.ManyToManyField(blank=True, related_name='portals_subscribed', to='user.Portal'),
        ),
    ]
