# Generated by Django 3.0.5 on 2020-05-06 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0014_auto_20200506_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portal',
            options={'verbose_name': '3. Portal', 'verbose_name_plural': '3. Portals'},
        ),
        migrations.AlterModelOptions(
            name='portalgoal',
            options={'verbose_name': '4. Portal Goal', 'verbose_name_plural': '4. Portal Goals'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '1. Profile', 'verbose_name_plural': '1. Profiles'},
        ),
        migrations.AlterModelOptions(
            name='virtualcard',
            options={'verbose_name': '2. Virtual Card', 'verbose_name_plural': '2. Virtual Cards'},
        ),
    ]
