# Generated by Django 3.0.5 on 2020-05-06 16:57

from django.db import migrations


def create_portals(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Portal = apps.get_model("user", "Portal")
    db_alias = schema_editor.connection.alias
    Portal.objects.all().delete()
    Portal.objects.using(db_alias).bulk_create([
        Portal(name="Build business credit with no personal guarantee"),
        Portal(name="Get a long term business loan "),
        Portal(name="Access immediate credit for your business "),
        Portal(name="Fix/Build my personal credit "),
        Portal(name="Make money as an affiliate partner "),
        Portal(name="Learn how to market my business "),
        Portal(name="Repair my business credit "),
        Portal(name="Get services you offer "),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0015_auto_20200506_1656'),
    ]

    operations = [
        migrations.RunPython(create_portals),
    ]
