# Generated by Django 3.0.5 on 2020-05-06 17:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0016_auto_20200506_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalgoal',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=200, null=True,
                                                populate_from='name', unique=True),
        ),
    ]
