# Generated by Django 3.0.5 on 2020-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0017_portalgoal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Unique portal code'),
        ),
    ]
