# Generated by Django 3.0.5 on 2020-05-21 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_auto_20200506_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duns', models.CharField(max_length=255, null=True, verbose_name='DUNS Number')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Last Name')),
                ('personal_address', models.CharField(max_length=255, null=True, verbose_name='Personal Address')),
                ('business_address', models.CharField(max_length=255, null=True, verbose_name='Business Address')),
                ('business_name', models.CharField(max_length=255, null=True, verbose_name='Business Name')),
                ('ein', models.CharField(max_length=255, null=True, verbose_name='EIN number')),
                ('billing_address', models.CharField(max_length=255, null=True, verbose_name='Billing Address')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5. Personal Information',
                'verbose_name_plural': '5. Personal Information',
            },
        ),
    ]
