# Generated by Django 3.0.5 on 2020-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0020_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='duns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DUNS Number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ein',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EIN number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Address'),
        ),
    ]
