# Generated by Django 3.0.5 on 2020-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0024_auto_20200521_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='personal_address',
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing City'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Country'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing State'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_street_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Line 1'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_street_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address Line 2'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='billing_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Zip Code'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal City'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Country'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal State'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_street_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Address Line 1'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_street_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Address Line 2'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Zip Code'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal City'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Country'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal State'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_street_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Address Line 1'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_street_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Address Line 2'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Zip Code'),
        ),
    ]
