# Generated by Django 3.0.5 on 2020-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0027_auto_20200521_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Phone'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='business_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Phone'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Personal Phone'),
        ),
    ]
