# Generated by Django 3.0.5 on 2020-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0029_usersteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='domain',
            field=models.CharField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')],
                                   default=(1, 'Not ordered'), max_length=500, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='fax_number',
            field=models.CharField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')],
                                   default=(1, 'Not ordered'), max_length=500, null=True, verbose_name='Fax numberx'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='phone',
            field=models.CharField(max_length=500, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='professional_email',
            field=models.CharField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')],
                                   default=(1, 'Not ordered'), max_length=500, null=True,
                                   verbose_name='Professional email'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='toll_free',
            field=models.CharField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')],
                                   default=(1, 'Not ordered'), max_length=500, null=True,
                                   verbose_name='Toll free number'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='website',
            field=models.CharField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')],
                                   default=(1, 'Not ordered'), max_length=500, null=True, verbose_name='Website'),
        ),
    ]
