# Generated by Django 3.0.5 on 2020-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0032_auto_20200606_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
