# Generated by Django 3.0.5 on 2020-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0033_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name'),
        ),
    ]
