# Generated by Django 3.0.5 on 2020-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0034_usersteps_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='industry_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Industry name'),
        ),
    ]
