# Generated by Django 3.0.5 on 2020-06-21 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0035_auto_20200620_1148'),
        ('user', '0036_auto_20200621_1827'),
    ]

    operations = [
    ]
