# Generated by Django 3.0.5 on 2020-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0037_merge_20200621_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='domain_name_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='fax_number_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='professional_email_address_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='toll_free_number_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name'),
        ),
    ]
