# Generated by Django 3.0.5 on 2020-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0038_auto_20200626_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='domain_name_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Actual website link'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='fax_number_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual fax number'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='professional_email_address_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Actual professinoal email address'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='toll_free_number_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Actual toll free number'),
        ),
    ]
