# Generated by Django 3.0.5 on 2020-06-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0039_auto_20200626_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersteps',
            old_name='fax_number_number',
            new_name='fax_number_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='professional_email_address_address',
            new_name='professional_email_address_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='toll_free_number_number',
            new_name='toll_free_number_act',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='domain_name_name',
            new_name='website_act',
        ),
        migrations.AddField(
            model_name='usersteps',
            name='domain_act',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Actual domain name'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
