# Generated by Django 3.0.5 on 2020-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0048_auto_20200719_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='domain_password',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain password'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='domain_username',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain username'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='email_password',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email password'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email username'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='toll_free_password',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Toll Free Number password'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='toll_free_username',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Toll Free Number username'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='website_password',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website password'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='website_username',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website username'),
        ),
    ]
