# Generated by Django 3.0.5 on 2020-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0049_auto_20200719_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='base_professional_mailing_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True,
                                   verbose_name='Base professional mailing address'),
        ),
    ]
