# Generated by Django 3.0.5 on 2020-07-26 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0052_auto_20200726_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersteps',
            old_name='fax_number_amount',
            new_name='fax_number_quantity',
        ),
        migrations.RenameField(
            model_name='usersteps',
            old_name='toll_free_amount',
            new_name='toll_free_quantity',
        ),
    ]
