# Generated by Django 3.0.5 on 2020-07-26 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0053_auto_20200726_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersteps',
            old_name='toll_free_prefix',
            new_name='toll_free_number_prefix',
        ),
    ]
