# Generated by Django 3.0.5 on 2020-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0055_newusercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whitelabel_portal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
