# Generated by Django 3.1.1 on 2020-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0056_profile_whitelabel_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expected_payout',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='residual_amount',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updates_made',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
