# Generated by Django 3.1.1 on 2020-09-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_auto_20200902_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
