# Generated by Django 3.1.1 on 2020-09-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_auto_20200903_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSteps',
        ),
    ]
