# Generated by Django 3.1.1 on 2020-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_delete_usersteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='billing_city',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing City'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='billing_country',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing Country'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='billing_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing Phone'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='billing_state',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing State'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='billing_street_address_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing Address Line 1'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='billing_zip_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Billing Zip Code'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_city',
            field=models.CharField(max_length=255, null=True, verbose_name='Business City'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_country',
            field=models.CharField(max_length=255, null=True, verbose_name='Business Country'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Business Phone'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_state',
            field=models.CharField(max_length=255, null=True, verbose_name='Business State'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='business_zip_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Business Zip Code'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='duns',
            field=models.CharField(max_length=255, null=True, verbose_name='DUNS Number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ein',
            field=models.CharField(max_length=255, null=True, verbose_name='EIN number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fax_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Fax Number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_city',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal City'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_country',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal Country'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal Phone'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_state',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal State'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_street_address_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal Address Line 1'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='personal_zip_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Personal Zip Code'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='toll_free_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Toll Free Number'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='Website'),
        ),
    ]
