# Generated by Django 3.1.1 on 2020-11-09 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0063_auto_20200918_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResourceCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '8. External Credential',
                'verbose_name_plural': '8. External Credentials',
            },
        ),
    ]
