# Generated by Django 3.1.1 on 2020-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_auto_20201109_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresourcecredentials',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
