# Generated by Django 3.1.4 on 2021-01-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_auto_20201214_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
