# Generated by Django 3.1.4 on 2021-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_profile_is_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='what_is_done',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_is_left',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_is_purchased',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_is_recommended',
            field=models.TextField(blank=True),
        ),
    ]
