# Generated by Django 3.1.4 on 2021-01-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_auto_20210121_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_goals_text',
            field=models.TextField(blank=True),
        ),
    ]
