# Generated by Django 3.1.1 on 2021-02-28 14:14

from django.db import migrations


def create_portals(apps, schema_editor):
    Portal = apps.get_model("user", "Portal")
    db_alias = schema_editor.connection.alias
    Portal.objects.all().delete()
    Portal.objects.using(db_alias).bulk_create([
        Portal(name="Build business credit with no personal guarantee", code="business_credit_with_nopg"),
        Portal(name="Get a long term business loan", code="long_term_loan"),
        Portal(name="Access immediate credit for your business", code="imediate_business_credit"),
        Portal(name="Fix/Build my personal credit", code="fix_personal_credit"),
        Portal(name="Learn how to market my business", code="business_marketing"),
        Portal(name="Repair my business credit", code="repair_business_credit"),
        Portal(name="Get services you offer", code="services_you_offer"),
        Portal(name="Get business insurance", code="business_insurance"),
        Portal(name="Need a merchant account", code="need_merchant_account"),
        Portal(name="Offering financing to customers", code="offer_financing2_customers"),
        Portal(name="Sign Up For Concierge Program", code="concierge_program_goal"),
        Portal(name="Become a white label partner ", code="become_whitelabel_partner_goal"),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0070_profile_user_goals_text'),
    ]

    operations = [
        migrations.RunPython(create_portals),
    ]
