# Generated by Django 3.0.5 on 2020-08-28 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_delete_tradelineorders'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradelineOrders',
            new_name='TradelineOrder',
        ),
    ]
