# Generated by Django 3.1.1 on 2020-09-04 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_delete_usersteps'),
        ('dynamic', '0019_subdomain_admins'),
        ('orders', '0003_tradelineorder_whitelabel_portal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelineorder',
            options={'verbose_name': '1. Tradeline Order', 'verbose_name_plural': '1. Tradeline Orders'},
        ),
        migrations.CreateModel(
            name='UserSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, verbose_name='User Email')),
                ('first_name', models.CharField(max_length=500, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=500, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=500, null=True, verbose_name='Phone Number')),
                ('website', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Website')),
                ('industry_name', models.IntegerField(blank=True, choices=[(1, 'Electrician'), (2, 'Gardener'), (3, 'Tattoo Artist'), (4, 'Photography'), (5, 'Limo Service'), (6, 'Nutrition Advisor'), (7, 'Life Coach'), (8, 'Veterinary clinic'), (9, 'Laundromat'), (10, 'Fitness Club'), (11, 'Dentist'), (12, 'Consulting'), (13, 'Auto Repair'), (14, 'Tutor'), (15, 'Bakery'), (16, 'Financial Advisor'), (17, 'Lawyer'), (18, 'Marketing Agency'), (19, 'Trucking'), (20, 'Locksmith'), (21, 'Medical Clinic'), (22, 'Dance Studio'), (23, 'Carpenter'), (24, 'Moving Company'), (25, 'Hair Salon'), (26, 'Cleaning Service'), (27, 'Car Dealer'), (28, 'Portfolio'), (29, 'Real Estate'), (30, 'Preschool'), (31, 'Spa Service'), (32, 'Physical Therapist')], default=1, null=True, verbose_name='Industry')),
                ('toll_free_number', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Toll free number')),
                ('fax_number', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Fax numberx')),
                ('domain', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Domain')),
                ('professional_email_address', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Professional email')),
                ('business_builder_program', models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Business Builder Program')),
                ('base_professional_mailing_address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Base professional mailing address')),
                ('domain_name', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name')),
                ('fax_number_act', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual fax number')),
                ('toll_free_number_act', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual toll free number')),
                ('professional_email_address_act', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual professional email address')),
                ('website_act', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual website link')),
                ('domain_act', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Actual domain name')),
                ('domain_dashboard', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain name dashboard')),
                ('email_provider', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email provider')),
                ('toll_free_username', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Toll Free Number username')),
                ('toll_free_password', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Toll Free Number password')),
                ('toll_free_number_prefix', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Toll Free prefix')),
                ('toll_free_quantity', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Toll Free amount')),
                ('fax_number_prefix', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Fax number prefix')),
                ('fax_number_quantity', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Fax amount amount')),
                ('website_username', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website username')),
                ('website_password', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website password')),
                ('domain_username', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain username')),
                ('domain_password', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Domain password')),
                ('email_username', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email username')),
                ('email_password', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email password')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('whitelabel_portal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.subdomain')),
            ],
            options={
                'verbose_name': '2. User Steps',
                'verbose_name_plural': '2. User steps',
            },
        ),
    ]
