# Generated by Django 3.0.5 on 2020-09-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0020_auto_20200905_0944'),
        ('orders', '0005_auto_20200904_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelineorder',
            name='whitelabel_portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.Subdomain'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='whitelabel_portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.Subdomain'),
        ),
    ]
