# Generated by Django 3.1.1 on 2020-09-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0021_subdomain_extensionvideo'),
        ('orders', '0006_auto_20200910_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='fax_number',
            field=models.IntegerField(choices=[(1, 'Not ordered'), (2, 'In progress'), (3, 'Done')], default=1, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.subdomain'),
        ),
    ]
