# Generated by Django 3.0.5 on 2020-09-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0021_subdomain_extensionvideo'),
        ('orders', '0007_auto_20200917_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelineorder',
            name='whitelabel_portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.Subdomain'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic.Subdomain'),
        ),
    ]
