# Generated by Django 3.1.1 on 2020-12-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201011_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='EIN',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='LLC',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='business_account',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='duns',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='marketing',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='merchant_account',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
        migrations.AddField(
            model_name='usersteps',
            name='tradelines',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='LLC'),
        ),
    ]
