# Generated by Django 3.1.1 on 2020-12-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20201208_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='EIN',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='EIN'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='business_account',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='Business Account'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='duns',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='DUNS'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='marketing',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='marketing'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='merchant_account',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='Merchant Account'),
        ),
        migrations.AlterField(
            model_name='usersteps',
            name='tradelines',
            field=models.IntegerField(choices=[(1, 'Not Ordered'), (2, 'Ordered'), (3, 'Done')], default=1, null=True, verbose_name='tradelines'),
        ),
    ]
