# Generated by Django 3.1.1 on 2020-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201209_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelineorder',
            name='last_purchased',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
