# Generated by Django 3.1.1 on 2020-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_tradelineorder_last_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelineorder',
            name='screenshot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
