# Generated by Django 3.1.1 on 2020-12-09 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_tradelineorder_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelineorder',
            name='expected_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
