# Generated by Django 3.1.1 on 2020-12-09 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20201209_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelineorder',
            name='expected_time',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='tradelineorder',
            name='last_purchased',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
