# Generated by Django 3.1.1 on 2020-12-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_customtier'),
        ('orders', '0020_auto_20201209_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelineorder',
            name='custom_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.customtier'),
        ),
    ]
