# Generated by Django 3.0.5 on 2020-05-14 13:10

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0019_auto_20200506_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelabelWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=500, null=True)),
                ('website_link', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelwebsite_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_website',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhitelabelPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_link', models.CharField(default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelportal_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_portal',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WhitelabelBusinessPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_login', models.CharField(max_length=500, null=True)),
                ('toll_free_number_login', models.CharField(max_length=500, null=True)),
                ('professional_email_address_login', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwhitelabelbusinesspackage_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_whitelabel_business_package',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalwebinar_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_webinars',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalsale_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_sale',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Residual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountofresiduals', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=500, null=True)),
                ('payout_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalresidual_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_residual',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaypalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalpaypalinformation_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_paypal_information',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50, null=True)),
                ('account_name', models.CharField(max_length=500, null=True)),
                ('amount_paid', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalpayment_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_payments',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaidProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, null=True)),
                ('client_email', models.CharField(max_length=50, null=True)),
                ('client_phone_number', models.CharField(max_length=50, null=True)),
                ('updates_made', models.CharField(max_length=500, null=True)),
                ('residual_amount', models.CharField(max_length=500, null=True)),
                ('expected_payout', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalpaidprogram_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_paid_program',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.CharField(max_length=50, null=True)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('order_amount', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalorder_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_order',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('business_package', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportallead_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_lead',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, null=True)),
                ('invoiceamount', models.CharField(max_length=50, null=True)),
                ('invoiceduedate', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('paynow', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalinvoice_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_invoice',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50, null=True)),
                ('client_email', models.CharField(max_length=50, null=True)),
                ('client_phone_number', models.CharField(max_length=50, null=True)),
                ('updates_made', models.CharField(max_length=500, null=True)),
                ('residual_amount', models.CharField(max_length=500, null=True)),
                ('expected_payout', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalfreeprogram_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_free_program',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, null=True)),
                ('created', models.CharField(default='', max_length=50, null=True)),
                ('applied', models.CharField(default='', max_length=50, null=True)),
                ('amount', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalcredit_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_credit',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BecomingAPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50, null=True)),
                ('business_number', models.CharField(max_length=500, null=True)),
                ('logo', models.FileField(null=True, upload_to=whitelabelpartnerportal.models.get_file_path)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalbecomingapartner_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_becomingapartner',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankPaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_number', models.CharField(max_length=500, null=True)),
                ('name_of_bank', models.CharField(max_length=500, null=True)),
                ('account_number', models.CharField(max_length=500, null=True)),
                ('name_on_bank_account', models.CharField(max_length=500, null=True)),
                ('your_address', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalbankpaymentinformation_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_bank_payment_information',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AffiliateResidual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50, null=True)),
                ('affiliate_name', models.CharField(max_length=500, null=True)),
                ('payout_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalaffiliateresidual_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_affiliate_residual',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AffiliateAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalaffiliateagents_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_affiliate_agents',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
