# Generated by Django 3.0.5 on 2020-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateagents',
            name='full_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateagents',
            name='phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateresidual',
            name='amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='becomingapartner',
            name='business_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='account_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='applied',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='created',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='freeprogram',
            name='client_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='freeprogram',
            name='client_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='freeprogram',
            name='client_phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoiceamount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business_package',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_placed',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidprogram',
            name='client_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidprogram',
            name='client_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidprogram',
            name='client_phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='residual',
            name='amountofresiduals',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
