# Generated by Django 3.0.5 on 2020-08-30 17:53

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_profile_whitelabel_portal'),
        ('whitelabelpartnerportal', '0003_auto_20200604_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUpProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=500, null=True)),
                ('client_email', models.CharField(max_length=500, null=True)),
                ('client_phone_number', models.CharField(max_length=500, null=True)),
                ('updates_made', models.CharField(max_length=500, null=True)),
                ('residual_amount', models.CharField(blank=True, max_length=500)),
                ('expected_payout', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalsignedupprogram_profile', to='user.Profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_signedup_program',
            },
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
