# Generated by Django 3.1.1 on 2020-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0004_signedupprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedupprogram',
            name='expected_payout',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='signedupprogram',
            name='residual_amount',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='signedupprogram',
            name='updates_made',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
    ]
