# Generated by Django 3.1.1 on 2020-09-13 12:21

from django.db import migrations, models
import django.db.models.deletion
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_delete_usersteps'),
        ('whitelabelpartnerportal', '0005_auto_20200902_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingRoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(blank=True, null=True)),
                ('amount_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_left', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_made', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
    ]
