# Generated by Django 3.1.1 on 2020-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0006_marketingroi'),
    ]

    operations = [
        migrations.AddField(
            model_name='residual',
            name='business_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residual',
            name='commissions_made',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residual',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='residual',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
