# Generated by Django 3.1.1 on 2020-12-09 21:53

from django.db import migrations, models
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0007_auto_20201115_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('desctiprion', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            bases=(whitelabelpartnerportal.models.ModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Webinar',
        ),
    ]
