# Generated by Django 3.1.1 on 2020-12-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0008_auto_20201209_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesale',
            old_name='desctiprion',
            new_name='description',
        ),
    ]
