# Generated by Django 3.1.1 on 2020-12-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0011_auto_20201215_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesale',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='price_lookup',
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wholesale',
            name='whitelabel_portal',
        ),
    ]
