# Generated by Django 3.1.1 on 2020-12-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0014_wholesaleorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
