# Generated by Django 3.1.4 on 2021-01-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0017_auto_20210103_1648'),
        ('whitelabelpartnerportal', '0017_wholesale_recurring'),
    ]

    operations = [
    ]
