# Generated by Django 3.1.4 on 2021-01-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0021_auto_20210121_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesale',
            name='recurring',
        ),
    ]
