# Generated by Django 3.1.4 on 2021-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0022_remove_wholesale_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='recurring',
            field=models.IntegerField(choices=[(1, 'One time'), (2, 'Monthly'), (3, 'Yearly')], null=True),
        ),
    ]
