# Generated by Django 3.1.4 on 2021-01-21 23:31

from django.db import migrations, models
import services.FileServices


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0024_auto_20210121_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='document',
            field=models.FileField(null=True, upload_to=services.FileServices.get_file_path),
        ),
    ]
