# Generated by Django 3.1.4 on 2021-01-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitelabelpartnerportal', '0026_auto_20210121_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
    ]
