# Generated by Django 3.2.5 on 2021-07-19 10:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import whitelabelpartnerportal.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20210714_1838'),
        ('whitelabelpartnerportal', '0029_auto_20210714_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZelleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zelle_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('zelle_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=500, null=True, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabelpartnerportalzelleinformation_profile', to='user.profile')),
            ],
            options={
                'db_table': 'whitelabelpartnerportal_zelle_information',
            },
            bases=(models.Model, whitelabelpartnerportal.models.ModelMixin),
        ),
    ]
