# Generated by Django 3.0.5 on 2020-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tradelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('tradeline_amount', models.IntegerField()),
                ('company_reports_to', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('video_link', models.URLField(max_length=300)),
            ],
        ),
    ]
