# Generated by Django 3.0.5 on 2020-08-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tradelines_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Tradelines',
            name='user',
        ),
    ]
