# Generated by Django 3.1.1 on 2020-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_tradelineorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradelines',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='tradelines',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
