# Generated by Django 3.1.1 on 2020-09-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200903_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelines',
            options={'verbose_name': '1. Tradeline', 'verbose_name_plural': '1. Tradelines'},
        ),
        migrations.AddField(
            model_name='tradelines',
            name='price_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
