# Generated by Django 3.1.1 on 2020-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200903_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelines',
            name='price_lookup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradelines',
            name='video_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
