# Generated by Django 3.1.1 on 2020-09-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200903_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelines',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='tradelines',
            name='tradeline_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
