# Generated by Django 3.1.1 on 2020-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200903_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('recurring', models.IntegerField(choices=[(1, 'One time'), (2, 'Monthly'), (3, 'Yearly')], null=True)),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('price_id', models.CharField(max_length=100, null=True)),
                ('price_lookup', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '2. User Steps',
                'verbose_name_plural': '2. User Steps',
            },
        ),
    ]
