# Generated by Django 3.1.1 on 2020-09-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_usersteps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSteps',
            new_name='UserStepsProduct',
        ),
    ]
