# Generated by Django 3.1.1 on 2020-09-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_subdomain_admins'),
        ('products', '0011_auto_20200903_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelines',
            name='whitelabel_portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
        migrations.AddField(
            model_name='userstepsproduct',
            name='whitelabel_portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
    ]
