# Generated by Django 3.1.1 on 2020-09-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_subdomain_admins'),
        ('products', '0012_auto_20200903_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelines',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
        migrations.AlterField(
            model_name='userstepsproduct',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.subdomain'),
        ),
    ]
