# Generated by Django 3.1.1 on 2020-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200903_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstepsproduct',
            name='name',
            field=models.CharField(choices=[('Website Monthly', 'Website Monthly'), ('Toll Free Number Monthly', 'Toll Free Number Monthly'), ('Fax Number Monthly', 'Fax Number Monthly'), ('Domain Monthly', 'Domain Monthly'), ('Professional Email Address Monthly', 'Professional Email Address Monthly'), ('Website Yearly', 'Website Yearly'), ('Toll Free Number Yearly', 'Toll Free Number Yearly'), ('Fax Number Yearly', 'Fax Number Yearly'), ('Domain Yearly', 'Domain Yearly'), ('Professional Email Address Yearly', 'Professional Email Address Yearly'), ('Business builder program Monthly', 'Business builder program Monthly'), ('Business builder program Yearly', 'Business builder program Yearly')], max_length=200),
        ),
    ]
