# Generated by Django 3.1.1 on 2020-09-05 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200904_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelines',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tradelines',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
