# Generated by Django 3.0.5 on 2020-09-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0020_auto_20200905_0944'),
        ('products', '0017_auto_20200905_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelines',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Subdomain'),
        ),
        migrations.AlterField(
            model_name='userstepsproduct',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Subdomain'),
        ),
    ]
