# Generated by Django 3.0.5 on 2020-09-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0023_subdomain_faq_page'),
        ('products', '0019_auto_20200918_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelines',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Subdomain'),
        ),
        migrations.AlterField(
            model_name='userstepsproduct',
            name='whitelabel_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Subdomain'),
        ),
    ]
