# Generated by Django 3.1.1 on 2020-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201011_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelines',
            name='tradeline_credit_amount',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
