# Generated by Django 3.1.1 on 2020-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_tradelines_tradeline_credit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelines',
            name='tier',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
